spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/LCPRealm
          jwk-set-uri: http://localhost:8080/auth/realms/LCPRealm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: ${CLIENT_ID:lenovo-client}
            client-secret: ${CLIENT_SECRET:}
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/LCPRealm/protocol/openid-connect/token

springdoc:
  swagger-ui:
    path: /swagger-ui.html

application.web-security-config:
  csrf-ignoring-url: /swagger-ui.html, /swagger-ui/**, /v3/api-docs/**
  custom-unsecured-endpoints:
  common-unsecured-endpoints: /v2/api-docs, /configuration/ui, /swagger-resources/**, /configuration/security, /swagger-ui.html, /webjars/**, /swagger-ui/**, /v3/api-docs/**
